### ISSUE TITLE
Where can I find the already generated keystore for the pre-registered TPP

### ISSUE THREAD

**Issue by darkedges** [ForgeRock/ForgeRock-OpenBanking-Sample#1]
Readme says there is a pre-registered TPP and keystore, but there is nothing in the repo.

Any ideas?

Thanks

**Comment by qcastel** [comment]
ah god, the read me. No that's true, there isn't.

Apologies if the readme is not accurate. You will need to generate keys with the OB directory first.

We are at the moment, testing a new ForgeRock directory. Good timing if you want to be one of the beta tester?

Can you find me on slack and I will add you to the beta room

**Comment by qcastel** [comment]
You can find me in here: https://open-banking-uk.slack.com/ or here https://openbankingsupport.slack.com/

**Comment by darkedges** [comment]
Okay I cannot sign up, as I don't have an email address that matches.

**Comment by qcastel** [comment]
The first one, the OB uk slack, is public

**Comment by darkedges** [comment]
open-banking-uk
```
If you have an @raidiam.com, @hsbc.com, or @aib.ie email address, you can create an account.
```
openbankingsupport
```
If you have an @openbanking.org.uk, @ostiasolutions.com, @wso2.com, @equifax.com, or @forgerock.com email address, you can create an account.
```

**Comment by qcastel** [comment]
Ok, I would need to invite you. Can you share with me your email address?

**Comment by darkedges** [comment]
nirving@darkedges.com
