### ISSUE TITLE
No AS_JWK_URI variable in POSTMAN environment file

### ISSUE THREAD

**Issue by aqeelsmith** [ForgeRock/ForgeRock-OpenBanking-Sample#4]
There is no mention of AS_JWK_URI in the POSTMAN environment file but the Hybrid flow call has a reference to this constant . Can you please check ?

**Comment by qcastel** [comment]
Hello @aqeelsmith,

You will now needs first to run the discovery requests, which would load the environment variables accordingly.

**Comment by aqeelsmith** [comment]
Thanks for the update .

Regards ,
Akhil
